addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.1.1")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.4.19")
addSbtPlugin("org.typelevel" % "sbt-typelevel-versioning" % "0.4.19")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci" % "0.4.19")
addSbtPlugin("dev.hnaderi" % "sbt-k8s-cookbook" % "0.1.7")
