version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:3-management
    #NOTE that hostname is crucial for persistent to work
    hostname: rabbit-node
    volumes:
      - rabbit:/var/lib/rabbitmq:rw
    ports:
      - 5672:5672
      - 15672:15672
  worker:
    image: kb-cli:latest
    command: service start -l 8080
    environment:
      - POSTGRES_HOST=postgres
      - RABBITMQ_HOST=rabbit
    deploy:
      replicas: 3
    restart: unless-stopped
volumes:
  pg_data:
  rabbit:
